### ISSUE TITLE
Net::OpenTimeout when calling `get_message_content`

### ISSUE THREAD

**Issue by dekaikiwi** [line/line-bot-sdk-ruby#84]
We seem to be getting timeouts every couple of calls to the `get_message_content` method.

Is there some outage going on on the Messaging API at the moment?

```
 TID-11lmcc WARN: Net::OpenTimeout: execution expired
2018-08-14T06:46:51.921442+00:00 app[sidekiq.1]: 4 TID-11lmcc WARN: /app/vendor/ruby-2.5.1/lib/ruby/2.5.0/net/http.rb:937:in `initialize'
2018-08-14T06:46:51.921444+00:00 app[sidekiq.1]: /app/vendor/ruby-2.5.1/lib/ruby/2.5.0/net/http.rb:937:in `open'
2018-08-14T06:46:51.921445+00:00 app[sidekiq.1]: /app/vendor/ruby-2.5.1/lib/ruby/2.5.0/net/http.rb:937:in `block in connect'
2018-08-14T06:46:51.921446+00:00 app[sidekiq.1]: /app/vendor/ruby-2.5.1/lib/ruby/2.5.0/timeout.rb:103:in `timeout'
2018-08-14T06:46:51.921447+00:00 app[sidekiq.1]: /app/vendor/ruby-2.5.1/lib/ruby/2.5.0/net/http.rb:935:in `connect'
2018-08-14T06:46:51.921449+00:00 app[sidekiq.1]: /app/vendor/ruby-2.5.1/lib/ruby/2.5.0/net/http.rb:920:in `do_start'
2018-08-14T06:46:51.921450+00:00 app[sidekiq.1]: /app/vendor/ruby-2.5.1/lib/ruby/2.5.0/net/http.rb:909:in `start'
2018-08-14T06:46:51.921451+00:00 app[sidekiq.1]: /app/vendor/ruby-2.5.1/lib/ruby/2.5.0/net/http.rb:1455:in `request'
2018-08-14T06:46:51.921452+00:00 app[sidekiq.1]: /app/vendor/bundle/ruby/2.5.0/gems/skylight-core-2.0.2/lib/skylight/core/probes/net_http.rb:27:in `request'
...
2018-08-14T06:46:51.921454+00:00 app[sidekiq.1]: /app/vendor/ruby-2.5.1/lib/ruby/2.5.0/net/http.rb:1213:in `get'
2018-08-14T06:46:51.921455+00:00 app[sidekiq.1]: /app/vendor/bundle/ruby/2.5.0/gems/line-bot-api-1.2.5/lib/line/bot/httpclient.rb:35:in `get'
2018-08-14T06:46:51.921456+00:00 app[sidekiq.1]: /app/vendor/bundle/ruby/2.5.0/gems/line-bot-api-1.2.5/lib/line/bot/request.rb:73:in `get'
2018-08-14T06:46:51.921457+00:00 app[sidekiq.1]: /app/vendor/bundle/ruby/2.5.0/gems/line-bot-api-1.2.5/lib/line/bot/client.rb:350:in `get'
2018-08-14T06:46:51.921458+00:00 app[sidekiq.1]: /app/vendor/bundle/ruby/2.5.0/gems/line-bot-api-1.2.5/lib/line/bot/client.rb:164:in `get_message_content'
```

**Comment by dekaikiwi** [comment]
Also posted to the Developers Q&A: https://www.line-community.me/question/5b728a26851f742a4ef1daa0

**Comment by kimoto** [comment]
Probably not occured server error at that time.
This issue is not ruby bot sdk issue. closed
